# Generated by Django 6.1.1 on 2026-09-20 13:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen')], default='mahasiswa', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AktivitasLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitas', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktivitas Log',
                'verbose_name_plural': 'Aktivitas Log',
                'db_table': 'aktivitas_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('validasi', 'Validasi Prestasi'), ('proyek', 'Proyek'), ('undangan', 'Undangan'), ('sistem', 'Sistem')], max_length=20)),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'db_table': 'notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('jurusan', models.CharField(max_length=100)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('bidang_keahlian', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_dosen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Dosen',
                'verbose_name_plural': 'Profil Dosen',
                'db_table': 'profil_dosen',
            },
        ),
        migrations.CreateModel(
            name='ProfilMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('prodi', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('ipk', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('poin', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Mahasiswa',
                'verbose_name_plural': 'Profil Mahasiswa',
                'db_table': 'profil_mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('lomba', 'Lomba/Kompetisi'), ('penelitian', 'Penelitian'), ('pengabdian', 'Pengabdian Masyarakat'), ('organisasi', 'Organisasi'), ('sertifikasi', 'Sertifikasi'), ('lainnya', 'Lainnya')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('penyelenggara', models.CharField(blank=True, max_length=200)),
                ('bukti_file', models.FileField(blank=True, null=True, upload_to='prestasi_bukti/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Validasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('catatan_validator', models.TextField(blank=True)),
                ('tanggal_validasi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validasi_prestasi', to='core.profildosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='core.profilmahasiswa')),
            ],
            options={
                'verbose_name': 'Prestasi',
                'verbose_name_plural': 'Prestasi',
                'db_table': 'prestasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tipe_proyek', models.CharField(choices=[('lomba', 'Lomba/Kompetisi'), ('penelitian', 'Penelitian'), ('pengabdian', 'Pengabdian Masyarakat'), ('asisten', 'Asisten Laboratorium'), ('startup', 'Startup/Bisnis'), ('lainnya', 'Lainnya')], max_length=20)),
                ('max_anggota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Terbuka'), ('full', 'Penuh'), ('closed', 'Ditutup'), ('completed', 'Selesai')], default='open', max_length=20)),
                ('persyaratan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyek_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyek',
                'verbose_name_plural': 'Proyek',
                'db_table': 'proyek',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Keahlian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_keahlian', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keahlian', to='core.profilmahasiswa')),
            ],
            options={
                'verbose_name': 'Keahlian',
                'verbose_name_plural': 'Keahlian',
                'db_table': 'keahlian',
                'unique_together': {('mahasiswa', 'nama_keahlian')},
            },
        ),
        migrations.CreateModel(
            name='AnggotaProyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Ketua'), ('member', 'Anggota')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('accepted', 'Diterima'), ('rejected', 'Ditolak'), ('invited', 'Diundang')], default='pending', max_length=10)),
                ('pesan_lamaran', models.TextField(blank=True)),
                ('tanggal_bergabung', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyek_diikuti', to='core.profilmahasiswa')),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='core.proyek')),
            ],
            options={
                'verbose_name': 'Anggota Proyek',
                'verbose_name_plural': 'Anggota Proyek',
                'db_table': 'anggota_proyek',
                'ordering': ['-created_at'],
                'unique_together': {('proyek', 'mahasiswa')},
            },
        ),
    ]
